### ISSUE TITLE
Unsupported class file major version 61 (Java 17)

### ISSUE THREAD

**Issue by kamko** [httptoolkit/jvm-http-proxy-agent#3]
Hello,

when trying to attach to Java 17 application it fails with several errors (probably trying to read multiple class files) but the common error is:
```
java.lang.IllegalArgumentException: Unsupported class file major version 61
	at tech.httptoolkit.relocated.org.objectweb.asm.ClassReader.<init>(ClassReader.java:10)
	at tech.httptoolkit.relocated.org.objectweb.asm.ClassReader.<init>(ClassReader.java:2)
	at tech.httptoolkit.relocated.org.objectweb.asm.ClassReader.<init>(ClassReader.java:1)
	at tech.httptoolkit.relocated.net.bytebuddy.utility.OpenedClassReader.of(OpenedClassReader.java:359)
```

The agent currently uses bytebuddy `1.10.20`
https://github.com/httptoolkit/jvm-http-proxy-agent/blob/main/build.gradle#L32

As Java 17 ASM is supported from [`1.10.21`](https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.10.21) upwards updating bytebuddy should suffice (and maybe also other dependencies).

If you give me a hint how I can test that this won't break anything locally I could provide the PR (not really complex one as it will probably just update dependencies).

**Comment by pimterry** [comment]
Ah, that makes sense! This was also just reported by @maxandersen [here](https://github.com/httptoolkit/httptoolkit/issues/215).

A PR to update the dep would be very welcome if you have a second to bump that & test it. It might be worth trying to update all the way to the latest bytebuddy, at least if that doesn't cause any issues. Looks like there's no obvious breaking changes so that should be easy enough. Note that all open-source contributors get [free HTTP Toolkit Pro](github.com/httptoolkit/httptoolkit#contributing-directly)!

You can run `./gradlew quickTest` to run the tests in this code after any changes, which will check nothing is completely broken against the demo app here.

You can also run `./gradlew shadowJar` to build the agent as `build/libs/http-proxy-agent-1.1.1-all.jar`. From there, you can copy it to overwrite HTTP Toolkit's (you can check the path by looking at `JAVA_TOOL_OPTIONS` inside an intercepted terminal), and then test manually using HTTP Toolkit against the targets you're interested in. You can also run `java -Djdk.attach.allowAttachSelf=true -jar ./agent.jar self-test` to test the agent attaching against itself.

**Comment by kamko** [comment]
Alrighty, I'll have a look at it tomorrow

// ot: I actually found this tool thanks to @maxandersen's [tweet ](https://twitter.com/maxandersen/status/1473066122719252486)

**Comment by maxandersen** [comment]
i've restarted httptoolkit but it still fails on this - wasn't it supposed to update automatically?

**Comment by pimterry** [comment]
Hi @maxandersen are you still seeing that? It should definitely be working now. You can check the specific HTTP Toolkit component versions by hovering over the HTTP logo in the app - the update you're looking for is server v1.6.0. If that hasn't updated yet, just give it a minute or two with the app open, and then restart it.

If it's updated and it's still not working, it would be very useful if you could share any error output that you have available.

**Comment by maxandersen** [comment]
The day I commented it said 1.5 and I restarted and waited multiple times. 

In the end I hand replaced the agent jar and all was good. 

So Afaics httptoolkit was/is not autouodating.

**Comment by pimterry** [comment]
> In the end I hand replaced the agent jar and all was good.

Ok, that confirms the agent JAR works at least, thanks! I was worried our fix itself was actually broken somewhere :smile:.

> So Afaics httptoolkit was/is not autouodating.

That's definitely unusual, but I can see from my stats that there's been many 1000s of other successful updates to 1.6.0 across all platforms, so the basic infrastructure is certainly working. There might've been some delay or a slow download in your case, I don't know (server updates are pulled from https://github.com/httptoolkit/httptoolkit-server/releases, and they're ~30MB, so they're fairly quick but not instant).

Give it a quick check when you get a minute. It's the server version specifically that's relevant here, not the desktop or UI version. If it is persistently not updating, it'd be great if you could open a separate issue, and include your system details (what OS & version are you using, which download did you use to install the app, anything else unusual what might be relevant). Thanks!
